homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.7926
  longitude: 7.3349
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 231
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: ha
  username: homeassistant
  password: ****
  discovery: true
  discovery_prefix: homeassistant


# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: random
  - platform: mqtt
    name: 'Room Humidity'
    state_topic: 'room/humidity'
  - platform: mqtt
    state_topic: 'mysensors-out/122/1/1/0/0'
    name: 'Temperature'
    unit_of_measurment: '°C'
  - platform: mqtt
    state_topic: 'mysensors-out/122/0/1/0/1'
    name: 'Humidity'
    unit_of_measurment: '%'

binary_sensor:
  - platform: mqtt
    state_topic: "mysensors-out/99/1/1/0/2"
    payload_on: 1
    payload_off: 0

switch:
  - platform: mqtt
    command_topic: "mysensors-in/99/1/1/1/2"
    payload_on: 1
    payload_off: 0

mysensors:
  gateways:
    - device: mqtt
      topic_in_prefix: 'mysensors-out'
      topic_out_prefix: 'mysensors-in'
  version: 2.0

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include automations.yaml